# Install or make sure these packages are installed

install.packages("foreign")
install.packages("ggplot2")
install.packages("Cairo")
install.packages("knitr")
install.packages("lme4")
install.packages("classInt")
install.packages("car")
install.packages("texreg")
install.packages("xtable")
install.packages("lmtest")
install.packages("pscl")
install.packages("sjstats")
install.packages("sjPlot")
install.packages("rmarkdown")
install.packages("arm")
